// This file was generated by wix-one-app-engine on Fri May 21 2021
// You can extend it if you want, but leave the defaults to be required from the engine config

module.exports = {
  ...require('./node_modules/wix-one-app-engine/tools/engine_cli/etc/metro.config'),
};
